# Generated by Django 5.2.5 on 2025-08-16 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('unit', models.CharField(default='unit', max_length=24)),
                ('stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('min_stock', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='housekeeping.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
