# Generated by Django 5.2.5 on 2025-08-16 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0002_inventoryitem_inventorymovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incidents/photos/')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SENT', 'Sent to area'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='housekeeping.room')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='housekeeping.housekeepingtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LINEN', 'Ropa blanca (sábanas/toallas)'), ('AMENITY', 'Amenity'), ('APPLIANCE', 'Electrodoméstico'), ('FURNITURE', 'Mueble'), ('OTHER', 'Otro')], max_length=16)),
                ('outcome', models.CharField(choices=[('LAUNDRY_TO_RETURN', 'Devolver a lavandería'), ('LAUNDRY_REJECTED', 'Rechazada por lavandería'), ('MISSING', 'Falta en la habitación'), ('BROKEN', 'Roto/dañado'), ('EXTRA_SUPPLY', 'Se requirió reposición extra')], max_length=24)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_lines', to='housekeeping.inventoryitem')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='housekeeping.incidentreport')),
            ],
        ),
    ]
